# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-16 10:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(blank=True, max_length=80, null=True)),
                ('address_line3', models.CharField(blank=True, max_length=70, null=True)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation_number', models.BigIntegerField()),
                ('affiliation_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=200)),
                ('board_abbreviation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('head_office', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PR', 'Private'), ('CG', 'Central Government'), ('SG', 'State Government'), ('SCG', 'Semi Central Government'), ('SSG', 'Semi State Government')], max_length=5)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.Address')),
                ('boards', models.ManyToManyField(blank=True, to='school_structure.Boards')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('PR', 'Private'), ('CG', 'Central Government'), ('SG', 'State Government'), ('SCG', 'Semi Central Government'), ('SSG', 'Semi State Government')], max_length=5)),
                ('education_type', models.CharField(choices=[('G', 'GIRLS'), ('B', 'BOYS'), ('CoEd', 'CO-ED')], max_length=5)),
                ('education_level', models.CharField(choices=[('PS', 'Play School'), ('PR', 'Primary'), ('SC', 'Secondary'), ('SR', 'Senior Secondary')], max_length=5)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.Address')),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.Affiliation')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.Group')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.IntegerField()),
                ('section', models.CharField(max_length=15)),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.School')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolStreams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=50)),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.School')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.School')),
                ('subject_hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='schoolclasses',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_structure.SchoolStreams'),
        ),
        migrations.AddField(
            model_name='schoolclasses',
            name='subjects',
            field=models.ManyToManyField(to='school_structure.SchoolSubjects'),
        ),
        migrations.AddField(
            model_name='districts',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.States'),
        ),
        migrations.AddField(
            model_name='cities',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.Districts'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.Boards'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.Cities'),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.Districts'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.States'),
        ),
    ]
